# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Platformio Package

on:
  release:
    types: [published]
env:
  PLATFORMIO_AUTH_TOKEN : ${secrets.PIO_TOKEN}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Update library.json version
      uses: jossef/action-set-json-field@v1
      with:
        file: library.json
        field: version
        value: ${{ github.event.release.tag_name }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio ci --project-option="lib_deps = https://github.com/steinwurf/bourne.git#9.0.0" --project-option="extra_scripts = pre_compiling_bourne.py" --keep-build-dir --build-dir ./ src
    - name: Package library
      run: pio package pack
    - name: Publish library
      run: pio package publish --owner thystreet --non-interactive
